services:
  - type: web
    name: hoja-de-vida
    env: python
    region: oregon
    plan: free
    buildCommand: >
      pip install -r requirements.txt &&
      cd mi_proyecto &&
      python check_db.py &&
      python manage.py migrate --noinput --verbosity 3 &&
      python create_superuser.py &&
      python manage.py collectstatic --noinput
    startCommand: bash -lc "cd mi_proyecto && python check_db.py && python manage.py migrate --noinput --verbosity 3 && python create_superuser.py && gunicorn app:app --workers 1 --timeout 60"
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        scope: runtime
        value: ${RENDER_EXTERNAL_URL}
      - key: SECRET_KEY
        scope: runtime
        value: ${SECRET_KEY}
      - key: DATABASE_URL
        fromDatabase:
          name: hoja-de-vida-db
          property: connectionString

  - type: pserv
    name: hoja-de-vida-db
    env: postgres
    region: oregon
    plan: free
    ipAllowList: []
