# Generated by Django 6.0 on 2026-02-02 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_cursorealizado_datospersonales_experiencialaboral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('iddocumento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('contenido', models.TextField(blank=True)),
                ('fechacreacion', models.DateField(auto_now_add=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Activar para que se vea en front')),
                ('orden', models.IntegerField(default=0)),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='portfolio.datospersonales')),
            ],
            options={
                'db_table': 'documentos',
                'ordering': ['orden', '-fechacreacion'],
            },
        ),
    ]
