# Generated by Django 6.0 on 2026-02-02 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoacademico',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.datospersonales'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.datospersonales'),
        ),
    ]
