# Generated by Django 6.0 on 2026-02-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_productoacademico_idperfilconqueestaactivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ventas_garage/'),
        ),
    ]
