# Generated by Django 6.0 on 2026-02-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_ventagarage_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='correoelectronico',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
