# Generated by Django 6.0 on 2026-02-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_datospersonales_correoelectronico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursorealizado',
            name='certificado_archivo',
            field=models.FileField(blank=True, null=True, upload_to='certificados_cursos/'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='experiencia_laboral/'),
        ),
    ]
