# Generated by Django 6.0 on 2026-02-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_cursorealizado_certificado_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconocimiento',
            name='certificado_archivo',
            field=models.FileField(blank=True, null=True, upload_to='certificados_reconocimientos/'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='tituloreconocimiento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
